name: Release Baton

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-baton:
    runs-on: ubuntu-latest
    steps:
      - uses: release-baton/release-baton@71f10a09c0b5161420efe386fdfa657f9f7d5688 # v1.1.1
        with:
          client-id: ${{ secrets.RELEASE_BATON_CLIENT_ID }}
          app-private-key: ${{ secrets.RELEASE_BATON_PRIVATE_KEY }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
